SELECT I.ANIMAL_ID AS ANIMAL_ID, I.ANIMAL_TYPE AS ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE REGEXP 'Intact' AND O.SEX_UPON_OUTCOME RLIKE 'Spayed|Neutered'
ORDER BY 1;