WITH RECURSIVE HOUR as (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1 FROM HOUR WHERE NUM < 23
)

SELECT H.NUM , CASE WHEN A.DATETIME IS NULL THEN 0 ELSE COUNT(*) END AS HOUR 
FROM HOUR H LEFT JOIN ANIMAL_OUTS A ON H.NUM = HOUR(A.DATETIME) 
GROUP BY H.NUM
ORDER BY 1;